import { Check, CircleAlert } from "lucide-react";
import type { GalleryDocument } from "@/lib/types";

export function InvoicePreview({ document, compact = false }: { document: GalleryDocument; compact?: boolean }) {
  const invoice = document.invoice;
  const vendor = invoice?.seller.name ?? document.vendor ?? "Asterion Components Pvt. Ltd.";
  const buyer = invoice?.buyer;
  const items = invoice?.items ?? [
    { description: "Servo drive assembly", quantity: "4", unit_price: "12500", line_total: "50000", gst_rate: "18", hsn_sac: "8479" },
    { description: "Encoder interface module", quantity: "8", unit_price: "3200", line_total: "25600", gst_rate: "18", hsn_sac: "8543" },
  ];
  const visibleItems = compact ? items.slice(0, 2) : items.slice(0, 5);
  const subtotal = invoice?.subtotal ?? "77600";
  const taxAmount = invoice ? Number(invoice.igst) + Number(invoice.cgst) + Number(invoice.sgst) : 7360;
  const taxLabel = invoice && Number(invoice.igst) === 0 ? "CGST + SGST" : "IGST";

  return (
    <div className={compact ? "manifest invoice-compact" : "manifest"} aria-label={`Preview of ${document.title}`}>
      <div className="invoice-accent" />
      <div className="invoice-head">
        <div><span className="invoice-logo">SF</span><strong>{vendor}</strong><small>Synthetic GST invoice · non-commercial</small></div>
        <div><h4>INVOICE</h4><span>{invoice?.invoice_number ?? document.invoiceNumber ?? "AST/26-27/0421"}</span></div>
      </div>
      <div className="invoice-meta-grid">
        <div><small>BILL TO</small><strong>{buyer?.name ?? "Meridian Robotics India"}</strong><span>{buyer ? `${buyer.address.line1}\n${buyer.address.city}, ${buyer.address.state} ${buyer.address.postal_code}` : "Hosur Industrial Estate\nTamil Nadu 635126"}</span></div>
        <div><small>ISSUED</small><strong>{formatDate(invoice?.invoice_date)}</strong><small>PLACE OF SUPPLY</small><strong>{invoice?.place_of_supply ?? "Tamil Nadu"}</strong></div>
      </div>
      <table className="invoice-table">
        <thead><tr><th>DESCRIPTION</th><th>QTY</th><th>RATE</th><th>AMOUNT</th></tr></thead>
        <tbody>
          {visibleItems.map((item, index) => <tr key={`${item.hsn_sac}-${index}`}><td>{item.description}</td><td>{item.quantity}</td><td>{formatMoney(item.unit_price)}</td><td>{formatMoney(item.line_total)}</td></tr>)}
        </tbody>
      </table>
      <div className="invoice-total">
        <div><span>GSTIN {invoice?.seller.gstin ?? "29AAKCA4821B1ZP"}</span><span>{invoice ? `Buyer GSTIN ${invoice.buyer.gstin}` : "Payment: NET 15"}</span></div>
        <div><span>Subtotal <strong>{formatMoney(subtotal)}</strong></span><span>{taxLabel} <strong>{formatMoney(taxAmount)}</strong></span><b>Total <strong>{document.amount ?? formatMoney(invoice?.grand_total ?? 84960)}</strong></b></div>
      </div>
      {!compact ? <div className="invoice-footer"><span>Generated by NV-SynthForge</span><span>synthetic · non-commercial</span></div> : null}
    </div>
  );
}

export function ValidationRules({ document }: { document: GalleryDocument }) {
  return (
    <ul className="rule-list">
      {document.rules.map((rule) => (
        <li key={rule.id}>
          <span className={rule.passed ? "rule-pass" : "rule-fail"}>{rule.passed ? <Check aria-hidden="true" /> : <CircleAlert aria-hidden="true" />}</span>
          <div><strong>{rule.label}</strong>{rule.detail ? <small>{rule.detail}</small> : null}</div>
        </li>
      ))}
    </ul>
  );
}

function formatMoney(value: string | number): string {
  const amount = Number(value);
  return Number.isFinite(amount) ? `₹${amount.toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}` : String(value);
}

function formatDate(value?: string): string {
  if (!value) return "13 Jul 2026";
  const date = new Date(`${value}T00:00:00`);
  return Number.isNaN(date.valueOf()) ? value : new Intl.DateTimeFormat("en-IN", { day: "2-digit", month: "short", year: "numeric" }).format(date);
}
