from __future__ import annotations

import random
from datetime import date, timedelta
from decimal import Decimal

from app.domain.invoice import Address, Invoice, InvoiceItem, Party

_STATES = [
    ("27", "Maharashtra", "Mumbai", "400051"),
    ("29", "Karnataka", "Bengaluru", "560001"),
    ("07", "Delhi", "New Delhi", "110001"),
    ("33", "Tamil Nadu", "Chennai", "600001"),
    ("24", "Gujarat", "Ahmedabad", "380001"),
]
_COMPANIES = ["Astra Analytics Pvt Ltd", "Bharat Compute Ltd", "Cobalt Retail Pvt Ltd", "Delta Robotics LLP", "Eka Cloud Services Pvt Ltd"]
_PRODUCTS = [
    ("GPU compute services", "998314", Decimal("1800.00"), Decimal("18")),
    ("AI workstation", "84715000", Decimal("125000.00"), Decimal("18")),
    ("Technical training", "999293", Decimal("12000.00"), Decimal("18")),
    ("Printed packaging", "481910", Decimal("850.00"), Decimal("12")),
]


def _gstin(state_code: str, index: int) -> str:
    pan_number = 1000 + (index % 9000)
    return f"{state_code}ABCDE{pan_number:04d}F1Z5"


class OfflineInvoiceGenerator:
    """Seeded, dependency-free invoice generation for demos and tests."""

    def generate(self, count: int, seed: int) -> list[Invoice]:
        if not 1 <= count <= 10_000:
            raise ValueError("count must be between 1 and 10000")
        rng = random.Random(seed)
        invoices: list[Invoice] = []
        for index in range(count):
            seller_state = rng.choice(_STATES)
            buyer_state = rng.choice(_STATES)
            item_count = rng.randint(1, 3)
            items = []
            for _ in range(item_count):
                description, hsn, price, rate = rng.choice(_PRODUCTS)
                quantity = Decimal(rng.randint(1, 5))
                items.append(InvoiceItem(description=description, hsn_sac=hsn, quantity=quantity, unit_price=price, gst_rate=rate))
            number = seed * 10_000 + index + 1
            invoices.append(
                Invoice(
                    invoice_number=f"INV-{seed:06d}-{index + 1:04d}",
                    invoice_date=date(2026, 1, 1) + timedelta(days=rng.randint(0, 364)),
                    seller=self._party(_COMPANIES[index % len(_COMPANIES)], seller_state, number),
                    buyer=self._party(_COMPANIES[(index + 2) % len(_COMPANIES)], buyer_state, number + 73),
                    items=items,
                    notes="Synthetic record generated by NV-SynthForge",
                )
            )
        return invoices

    @staticmethod
    def _party(name: str, state: tuple[str, str, str, str], index: int) -> Party:
        code, state_name, city, postal = state
        return Party(
            name=name,
            gstin=_gstin(code, index),
            address=Address(line1=f"{(index % 199) + 1}, Innovation Park", city=city, state=state_name, state_code=code, postal_code=postal),
        )
